-- Each new term in the Fibonacci sequence is generated by adding the
-- previous two terms. By starting with 1 and 2, the
-- first 10 terms will be: 1, 2, 3, 5, 8, 13, 21,
-- 34, 55, 89, ...
-- By considering the terms in the Fibonacci
-- sequence whose values do not exceed four million,
-- find the sum of the even-valued terms.

fibsum :: Integral a => a -> a
fibsum limit = sum $ filter even $ fib 1 2
    where
  fib x y
      | y <= limit = [x] ++ fib y (x + y) 
      | otherwise = [x] -- stop once either addend exceeds limit

solution = fibsum $ round 4e6
